spring:
  application:
    name: smart-campus-navigator
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_campus_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

jwt:
  secret: SmartCampusNavigatorSecretKey2024VeryLongStringForHS256AlgorithmSecurity
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    persist-authorization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.megh.smartcampus: INFO
    org.springframework.security: WARN
